---
title: "Organização de Bancos de Dados"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Todo e qualquer projeto de pesquisa terá como uma parte importante a coleta de dados. Os dados obtidos em amostragens (organismos bentos, peixes recifas) são de alguma maneira anotados em campo e posteriormente digitaslizados em forma de planilhas (excel, e.g.). Após a digitação dos dados, o passo seguinte é explorarmos de alguma maneira estas informações.
As informações podem ser visualizadas em gráficos em tabelas.

No entanto, a leitura dos dados pelo olhar humano e a leitura realizada por uma "máquina" são realizadas de maneiras completamente diferentes. A leitura huamanda de planilhas é visual, tendemos a destacar informações com cores e tabulações. Já a leitura dos dados realzadas por algiritmos em nossos computadores opera de uma maneira completamente diferente. A leitura é realisada pela codificação da informação o que é de difícil leitura para humanos.

Para que possamos processar os dados coletados e estes possam ser compreendidos por algoritmos, precisamos estruturá-los de forma que possam ser lidos, formatados e recodificados para a leitura humana. Nesse sentido, o objetivo desta sessão e apresentar um guia de boas práticas de formatação de planilhas de dados. 


## Objetivos
  + Criar um banco de dados organizado que possa ser lido por qualquer algoritmo
  + Formatos
  + Identificar armadilhas no momento da formatação
  + Estratégias para minimização de erros de digitação
  + Metadados - Read Me


## Formatação de Planilhas


### Problemas de Formatação
  + Leitura Humana vs. Leitura dos Computadores

### Formatos de planilhas
 
  + Largo: Entende-se pela formatos onde cada linha é uma unidade amostral e as coluna as variáveis. Cada unidade amostral adicionada acrescenta uma linha para baixo. Cada variável adicionada acrescenta uma coluna.
  
  fig
    
  + Longo: 
  
  fig
    
  + mixto (CPCe, PhotoQuad)

  fig



### Logica de construção Hierárquica

O emprego de uma lógica hierárquica na construção dos bancos de dados ajuda muito no momento da digitação dos dados e na compreessão da estruturea dos dados.

### Nomes de Variáveis

### Estados de Variáveis


## Datas

## Controle de Qualidade

 + Nome de espécies
 
 + Nomes de locais
 
 + Coordendas

## Exportação de Dados